config/routes.rb
Rails.application.routes.draw do
  root 'crypto_currencies#home'
  get '/about', to: 'crypto_currencies#about'
  get '/details', to: 'crypto_currencies#details'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/crypto_currencies_controller.rb
class CryptoCurrenciesController < ApplicationController
  def home
    response = HTTParty.get('https://api.coinmarketcap.com/v1/ticker/')
    @cryptos_list = JSON.parse(response.body)
  end

  def about; end

  def details; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crypto_currencies_helper.rb
module CryptoCurrenciesHelper
end

app/views/crypto_currencies/about.html.erb
<% provide(:title, "About") %>
<% provide(:body_class, "profile-page") %>

<div class="wrapper">
  <div class="header header-filter about-header"></div> <!-- /header -->
  <div class="main main-raised">
    <div class="profile-content">
      <div class="container">

        <div class="row">
          <div class="profile">
            <div class="avatar">
              <%= image_tag 'btc.png', alt: 'Bitcoin logo', class: 'img-circle img-responsive img-raised' %>
            </div>
            <div class="name">
              <h3 class="title">About</h3>
            </div>
          </div>
        </div> <!-- /row -->

        <div class="description text-center">
          <p>This is just a simple web app designed to track cryptocurrencies prices. Here are some experts views on the subject. </p>
        </div>

        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <div class="profile-tabs">
              <div class="nav-align-center">

                <ul class="nav nav-pills" role="tablist">
                  <li class="active">
                    <a href="#studio" role="tab" data-toggle="tab">
                      <i class="material-icons">camera</i> Doc
                    </a>
                  </li>
                  <li>
                    <a href="#work" role="tab" data-toggle="tab">
                      <i class="material-icons">palette</i> Work
                    </a>
                  </li>
                  <li>
                    <a href="#shows" role="tab" data-toggle="tab">
                      <i class="material-icons">favorite</i> Favorite
                    </a>
                  </li>
                </ul>

                <div class="tab-content gallery">
                  <div class="tab-pane active" id="studio">
                    <div class="row">
                      <div class="col-md-12">
                        <%= image_tag 'marty.jpg', alt: 'back to the future meme', class: 'img-rounded' %>
                      </div>

                    </div> <!-- /row -->
                  </div>
                  <div class="tab-pane text-center" id="work">
                    <div class="row">
                      <div class="col-md-6">
                        <img src="" class="img-rounded" />
                        <img src="" class="img-rounded" />
                        <img src="" class="img-rounded" />
                      </div>
                      <div class="col-md-6">
                        <img src="" class="img-rounded" />
                        <img src="" class="img-rounded" />
                      </div>
                    </div> <!-- /row -->
                  </div>
                  <div class="tab-pane text-center" id="shows">
                    <div class="row">
                      <div class="col-md-6">
                        <img src="" class="img-rounded" />
                        <img src="" class="img-rounded" />
                      </div>
                      <div class="col-md-6">
                        <img src="" class="img-rounded" />
                        <img src="" class="img-rounded" />
                        <img src="" class="img-rounded" />
                      </div>
                    </div> <!-- /row -->
                  </div>
                </div>
              </div>
            </div>
            <!-- End Profile Tabs -->
          </div>
        </div> <!-- /row -->

      </div> <!-- /container -->
    </div>
  </div>

</div> <!-- /wrapper -->

app/views/crypto_currencies/details.html.erb
<% provide(:title, "Details") %>

<body class="landing-page">

    <div class="wrapper">
        <div class="header header-filter" style="background-image: url('https://images.unsplash.com/photo-1423655156442-ccc11daa4e99?crop=entropy&dpr=2&fit=crop&fm=jpg&h=750&ixjsv=2.1.0&ixlib=rb-0.3.5&q=50&w=1450');">
            <div class="container">
                <div class="row">
          <div class="col-md-6">
            <h1 class="title">Template</h1>
                      <h4>Every landing page needs a small description after the big bold title, that's why we added this text here. Add here all the information that can make you or your product create the first impression.</h4>
                      <br />
                      <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" class="btn btn-danger btn-raised btn-lg">
              <i class="fa fa-play"></i> Watch video
            </a>
          </div>
                </div>
            </div>
        </div>

    <div class="main main-raised">
      <div class="container">
          <div class="section text-center section-landing">
                  <div class="row">
                      <div class="col-md-8 col-md-offset-2">
                          <h2 class="title">Let's talk product</h2>
                          <h5 class="description">This is the paragraph where you can write more details about your product. Keep you user engaged by providing meaningful information. Remember that by this time, the user is curious, otherwise he wouldn't scroll to get here. Add a button if you want the user to see more.</h5>
                      </div>
                  </div>

          <div class="features">
            <div class="row">
                        <div class="col-md-4">
                <div class="info">
                  <div class="icon icon-primary">
                    <i class="material-icons">chat</i>
                  </div>
                  <h4 class="info-title">First Feature</h4>
                  <p>Divide details about your product or agency work into parts. Write a few lines about each one. A paragraph describing a feature will be enough.</p>
                </div>
                        </div>
                        <div class="col-md-4">
                <div class="info">
                  <div class="icon icon-success">
                    <i class="material-icons">verified_user</i>
                  </div>
                  <h4 class="info-title">Second Feature</h4>
                  <p>Divide details about your product or agency work into parts. Write a few lines about each one. A paragraph describing a feature will be enough.</p>
                </div>
                        </div>
                        <div class="col-md-4">
                <div class="info">
                  <div class="icon icon-danger">
                    <i class="material-icons">fingerprint</i>
                  </div>
                  <h4 class="info-title">Third Feature</h4>
                  <p>Divide details about your product or agency work into parts. Write a few lines about each one. A paragraph describing a feature will be enough.</p>
                </div>
                        </div>
                    </div>
          </div>
              </div>

            <div class="section text-center">
                  <h2 class="title">Here is our team</h2>

          <div class="team">
            <div class="row">
              <div class="col-md-4">
                          <div class="team-player">
                              <img src="../assets/img/avatar.jpg" alt="Thumbnail Image" class="img-raised img-circle">
                              <h4 class="title">Gigi Hadid <br />
                    <small class="text-muted">Model</small>
                  </h4>
                              <p class="description">You can write here details about one of your team members. You can give more details about what they do. Feel free to add some <a href="#">links</a> for people to be able to follow them outside the site.</p>
                  <a href="#pablo" class="btn btn-simple btn-just-icon"><i class="fa fa-twitter"></i></a>
                  <a href="#pablo" class="btn btn-simple btn-just-icon"><i class="fa fa-instagram"></i></a>
                  <a href="#pablo" class="btn btn-simple btn-just-icon btn-default"><i class="fa fa-facebook-square"></i></a>
                          </div>
                      </div>
                      <div class="col-md-4">
                          <div class="team-player">
                              <img src="../assets/img/christian.jpg" alt="Thumbnail Image" class="img-raised img-circle">
                              <h4 class="title">Christian Louboutin<br />
                    <small class="text-muted">Designer</small>
                  </h4>
                              <p class="description">You can write here details about one of your team members. You can give more details about what they do. Feel free to add some <a href="#">links</a> for people to be able to follow them outside the site.</p>
                  <a href="#pablo" class="btn btn-simple btn-just-icon"><i class="fa fa-twitter"></i></a>
                  <a href="#pablo" class="btn btn-simple btn-just-icon"><i class="fa fa-linkedin"></i></a>
                          </div>
                      </div>
                      <div class="col-md-4">
                          <div class="team-player">
                              <img src="../assets/img/kendall.jpg" alt="Thumbnail Image" class="img-raised img-circle">
                              <h4 class="title">Kendall Jenner<br />
                    <small class="text-muted">Model</small>
                  </h4>
                              <p>You can write here details about one of your team members. You can give more details about what they do. Feel free to add some <a href="#">links</a> for people to be able to follow them outside the site.</p>
                  <a href="#pablo" class="btn btn-simple btn-just-icon"><i class="fa fa-google-plus"></i></a>
                  <a href="#pablo" class="btn btn-simple btn-just-icon"><i class="fa fa-youtube-play"></i></a>
                  <a href="#pablo" class="btn btn-simple btn-just-icon btn-default"><i class="fa fa-twitter"></i></a>
                          </div>
                      </div>
            </div>
          </div>

              </div>


            <div class="section landing-section">
                  <div class="row">
                      <div class="col-md-8 col-md-offset-2">
                          <h2 class="text-center title">Work with us</h2>
              <h4 class="text-center description">Divide details about your product or agency work into parts. Write a few lines about each one and contact us about any further collaboration. We will responde get back to you in a couple of hours.</h4>
                          <form class="contact-form">
                              <div class="row">
                                  <div class="col-md-6">
                    <div class="form-group label-floating">
                      <label class="control-label">Your Name</label>
                      <input type="email" class="form-control">
                    </div>
                                  </div>
                                  <div class="col-md-6">
                    <div class="form-group label-floating">
                      <label class="control-label">Your Email</label>
                      <input type="email" class="form-control">
                    </div>
                                  </div>
                              </div>

                <div class="form-group label-floating">
                  <label class="control-label">Your Messge</label>
                  <textarea class="form-control" rows="4"></textarea>
                </div>

                              <div class="row">
                                  <div class="col-md-4 col-md-offset-4 text-center">
                                      <button class="btn btn-primary btn-raised">
                      Send Message
                    </button>
                                  </div>
                              </div>
                          </form>
                      </div>
                  </div>

              </div>
          </div>

    </div>

      <footer class="footer">
          <div class="container">
              <nav class="pull-left">
                  <ul>
                      <li>
                          <a href="http://www.creative-tim.com">
                              Creative Tim
                          </a>
                      </li>
            <li>
                          <a href="http://presentation.creative-tim.com">
                             About Us
                          </a>
                      </li>
                      <li>
                          <a href="http://blog.creative-tim.com">
                             Blog
                          </a>
                      </li>
                      <li>
                          <a href="http://www.creative-tim.com/license">
                              Licenses
                          </a>
                      </li>
                  </ul>
              </nav>
              <div class="copyright pull-right">
                  &copy; 2017, made with <i class="fa fa-heart heart"></i> by <%= link_to "Durev", "https://github.com/Durev", target: "_blank" %>
              </div>
          </div>
      </footer>

  </div>
</body>

app/views/crypto_currencies/home.html.erb
<% provide(:title, "Home") %>
<% provide(:body_class, "landing-page") %>

<div class="wrapper">
  <div class="header header-filter" style="background-image: url('https://images.unsplash.com/photo-1423655156442-ccc11daa4e99?crop=entropy&dpr=2&fit=crop&fm=jpg&h=750&ixjsv=2.1.0&ixlib=rb-0.3.5&q=50&w=1450');">
    <div class="container">

      <div class="row">
        <div class="col-md-6">
          <h1 class="title">CryptoTracker</h1>
          <h4>Check prices trends, track your favourite cryptocurrencies and get notified when the prices reach a limit.</h4>
          <br />
          <a href="#" class="btn btn-danger btn-raised btn-lg">
            <i class="fa fa-play"></i> Signup
          </a>
        </div> <!-- /col-md-6 -->
      </div> <!-- /row -->

    </div> <!-- /container -->
  </div> <!-- /header -->

  <div class="main main-raised">
    <div class="container">
      <div class="section text-center section-landing">

        <div class="row">
          <div class="col-md-8 col-md-offset-2">
            <h2 class="title">Crypto list</h2>
            <h5 class="description">Here are the last prices</h5>
          </div>
        </div>
        <hr>

        <% @cryptos_list.each do |crypto| %>

          <div class="row crypto-data">
            <div class="col-md-4">
              <h2 class="title"><%= crypto["name"] %></h2>
              <h3><%= crypto["symbol"] %></h3>
            </div>
            <div class="col-md-4">
              <h3><%= crypto["price_usd"] %> $</h3>
            </div>
            <div class="col-md-4">

              <!-- Refactorization needed -->
              <p>
                24 h :
                <% if crypto["percent_change_24h"].to_f >= 0 %>
                  <span class="trending-up">
                    + <%= crypto["percent_change_24h"] %> %
                    <i class="material-icons">trending_up</i>
                  </span>
                <% else %>
                  <span class="trending-down">
                    <%= crypto["percent_change_24h"] %> %
                    <i class="material-icons">trending_down</i>
                  </span>
                <% end %>
              </p>

              <p>
                7 d :
                <% if crypto["percent_change_7d"].to_f >= 0 %>
                  <span class="trending-up">
                    + <%= crypto["percent_change_7d"] %> %
                    <i class="material-icons">trending_up</i>
                  </span>
                <% else %>
                  <span class="trending-down">
                    <%= crypto["percent_change_7d"] %> %
                    <i class="material-icons">trending_down</i>
                  </span>
                <% end %>
              </p>

            </div>
          </div> <!-- /row -->
          <hr>

        <% end %>

      </div> <!-- /section -->
    </div> <!-- /container -->
  </div> <!-- /main -->

</div> <!-- /wrapper -->

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <nav class="pull-left">
      <ul>
        <li>
          <%= link_to "Hello", "#" %>
        </li>
        <li>
          <%= link_to "About Us", "#" %>
        </li>
        <li>
          <%= link_to "Blog", "#" %>
        </li>
        <li>
          <%= link_to "Licenses", "#" %>
        </li>
      </ul>
    </nav>
      <div class="copyright pull-right">
          2017, made with <i class="fa fa-heart heart"></i> by <%= link_to "Durev", "https://github.com/Durev", target: "_blank" %>
      </div>
  </div> <!-- /container -->
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-transparent navbar-fixed-top navbar-color-on-scroll">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "CryptoTracker", root_url, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="navigation-example">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Home",   root_url %>
        </li>
        <li>
          <%= link_to "About",   about_url %>
        </li>
        <li>
          <a href="https://twitter.com/" target="_blank" class="btn btn-simple btn-white btn-just-icon">
            <i class="fa fa-twitter"></i>
          </a>
        </li>
        <li>
          <a href="https://www.facebook.com/" target="_blank" class="btn btn-simple btn-white btn-just-icon">
            <i class="fa fa-facebook-square"></i>
          </a>
        </li>
        <li>
          <a href="https://www.instagram.com/" target="_blank" class="btn btn-simple btn-white btn-just-icon">
            <i class="fa fa-instagram"></i>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | CryptoTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- From bootstrap template -->
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

    <!--     Fonts and icons     -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
      <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
  </head>

  <body class="<%= yield(:body_class) %>">
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>